services:
  - type: web
    name: mvp-discord-bot
    env: python
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: MVP_GUILD_ID
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.9
